/**
 * Starting SkynetOS: one copy at a time, the newest wins, and optionally at Windows login.
 *
 * William: "make it so skynetOS boots automatically at startup but can detect an already open
 * version, closes it, and opens a refreshed version."
 *
 * Pure: the registry command lines, the hidden-window login script, and reading `reg query` back.
 * The two callers are src/main/services/autostart.ts (the LOOK panel's checkbox) and
 * tools/autostart.ts (`npm run autostart:on|off|status`). Both must write exactly the same Run
 * value, or the checkbox would read the script's work as "someone else's".
 */

const BACKSLASH = String.fromCharCode(92);

/** Per-user, so no administrator is needed to set it and no other account is affected. */
export const RUN_KEY = ['HKCU', 'Software', 'Microsoft', 'Windows', 'CurrentVersion', 'Run'].join(BACKSLASH);
export const RUN_VALUE = 'SkynetOS';

export interface AutostartState {
  /** False off Windows, where there is no Run key. */
  supported: boolean;
  /** A `SkynetOS` Run value exists. */
  enabled: boolean;
  /** The command it holds, as read back from the registry. */
  command: string | null;
  /** It is exactly this machine's own login script, and that script exists. */
  current: boolean;
}

/**
 * The smoke harness never takes part in the single-instance hand-over. A screenshot run beside
 * William's open SkynetOS would otherwise ask his copy to close.
 */
export function singleInstanceApplies(env: Record<string, string | undefined>): boolean {
  return !env['SKYNET_SMOKE_DIR'];
}

/* Argument ARRAYS for execFile. A shell string would put a path with spaces through cmd.exe. */
export function regQueryArgs(): string[] {
  return ['query', RUN_KEY, '/v', RUN_VALUE];
}

export function regAddArgs(data: string): string[] {
  return ['add', RUN_KEY, '/v', RUN_VALUE, '/t', 'REG_SZ', '/d', data, '/f'];
}

export function regDeleteArgs(): string[] {
  return ['delete', RUN_KEY, '/v', RUN_VALUE, '/f'];
}

/**
 * What the Run value holds: wscript running the generated login script. wscript is a GUI host, so
 * nothing flashes on screen at login. Both paths are quoted: the script lives under
 * `C:\Users\<name>\AppData`, where a space may appear.
 */
export function autostartCommand(wscriptExe: string, vbsPath: string): string {
  return `"${wscriptExe}" "${vbsPath}"`;
}

/**
 * The Run value for an INSTALLED SkynetOS: the program itself, quoted. No login script and no node:
 * there is nothing to build, and the exe sits at the same per-user path after every update. The dev
 * copy keeps `autostartCommand`, because starting from source means building first (docs/09).
 */
export function installedAutostartCommand(exePath: string): string {
  return `"${exePath}"`;
}

/** A VBScript string literal: wrapped in quotes, with any quote inside doubled. */
function vbsString(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

/**
 * The login script. Generated per machine into userData, never committed: it holds absolute local
 * paths, and the repo is public. `sh.Run <command>, 0, False`: 0 is a hidden window, False means
 * do not wait. node runs tools/boot.mjs, which builds and starts SkynetOS and then exits.
 */
export function bootVbs(paths: { node: string; script: string; repo: string }): string {
  return [
    "' SkynetOS - generated by the 'Start SkynetOS with Windows' switch or npm run autostart:on.",
    "' Regenerated every time it is switched on. Starts SkynetOS at login with no console window.",
    'Option Explicit',
    'Dim sh',
    'Set sh = CreateObject("WScript.Shell")',
    `sh.CurrentDirectory = ${vbsString(paths.repo)}`,
    `sh.Run ${vbsString(`"${paths.node}" "${paths.script}"`)}, 0, False`,
    ''
  ].join('\r\n');
}

/**
 * The data of the `SkynetOS` value from `reg query` output, or null when it is not there. reg.exe
 * prints `    SkynetOS    REG_SZ    <data>` under the key's name.
 */
export function parseRunValue(stdout: string): string | null {
  const line = stdout.split(/\r?\n/).find((l) => new RegExp(`^\\s*${RUN_VALUE}\\s+REG_(?:EXPAND_)?SZ\\s`).test(l));
  if (!line) return null;
  const match = /REG_(?:EXPAND_)?SZ\s+(.*)$/.exec(line);
  return match ? (match[1] ?? '').trim() : null;
}
