import type { TargetState } from '@shared/targets.js';

/**
 * FACE-BOOT.md: what the Face needs, in the one place it can reach.
 *
 * ── The constraint ────────────────────────────────────────────────────────────────────────────
 *
 * The Face is a claude.ai conversation. It can fetch only a URL that William pasted or that
 * appeared in an earlier fetch result; it cannot construct one, and GitHub robots-blocks `tree/`
 * pages, so it cannot list a directory. From a cold start, everything it can reach is the repo's
 * root page, which links every ROOT-level file, plus one hop from there. So this file lives at the
 * root, and it carries its content inline instead of linking to it.
 *
 * ── Generated, never authored ─────────────────────────────────────────────────────────────────
 *
 * Like assets/atlas/, it is a bake artefact: `npm run face:bake` writes it, the pre-commit hook
 * (`npm run face:hook`) keeps it current, and nobody edits it by hand. Section 3, the board truth,
 * is why it exists: what is broken RIGHT NOW, generated rather than remembered, so the Face stops
 * reasoning from stale documents. It said it did exactly that, and got it wrong.
 *
 * Everything here is pure. tools/face-bake.ts does the reading and the resolving.
 */

export interface BootMail {
  file: string;
  subject: string;
  from: string;
  sentAt: string;
  body: string;
}

export interface BootFault {
  nodeId: string;
  label: string;
  kind: string;
  state: TargetState;
  target: string;
}

export interface BootBoard {
  id: string;
  name: string;
  file: string;
  nodeCount: number;
  edgeCount: number;
  faults: BootFault[];
  provisional: { nodeId: string; label: string; kind: string }[];
}

export interface FaceBootInput {
  bakedAt: string;
  machine: string;
  /** codex/index.md, or null when it is missing. */
  index: string | null;
  /** Everything in codex/mailbox/to-face/, in any order. */
  mail: BootMail[];
  boards: BootBoard[];
  /** handoff.md, or null when it is missing. */
  handoff: string | null;
  /** codex/face-brief.md, or null when no standing orders have been written. */
  standing: string | null;
  /** The skynet MCP tool names. */
  tools: string[];
}

export const BOOT_MARKER =
  '<!-- GENERATED by `npm run face:bake` (tools/face-bake.ts). Do not edit by hand: the next bake overwrites it. -->';

/** The newest this many messages are inlined whole; the rest are counted. */
export const MAIL_LIMIT = 10;

/**
 * States that mean "this node does not reach its target".
 *
 * `outside-dev-root` does reach it (it is confirmed on every click, which is not a fault), and
 * `none` has no target to reach.
 */
export const FAULT_STATES: readonly TargetState[] = ['unset', 'missing', 'invalid', 'unknown'];

const BAKED_LINE = /^Written for JARVIS Head\b.*$/m;

export function nodeLabel(node: { id: string; designator?: string; name: string }): string {
  return node.designator ? `${node.designator} ${node.name}` : node.name;
}

/**
 * A fence the text cannot close from inside. Mail and the index are markdown with their own
 * fences in them, and a body that ends the block early spills the rest of itself into the page.
 */
function fenced(text: string): string {
  const longest = Math.max(0, ...[...text.matchAll(/`+/g)].map((m) => m[0].length));
  const fence = '`'.repeat(Math.max(4, longest + 1));
  return `${fence}markdown\n${text.replace(/\r\n/g, '\n').trimEnd()}\n${fence}`;
}

/**
 * handoff.md, compressed rather than duplicated: its lead block, and the titles under "What is
 * next". The full file is one hop from the repo root if the Face wants the rest.
 */
export function handoffState(md: string | null): string {
  if (!md?.trim()) return 'handoff.md is missing. The Hands have not recorded their state.';
  const lines = md.replace(/\r\n/g, '\n').split('\n');

  const start = lines.findIndex((l) => /^#\s/.test(l));
  const lead: string[] = [];
  for (let i = start + 1; i < lines.length; i++) {
    const line = lines[i] ?? '';
    if (/^---\s*$/.test(line) || /^##\s/.test(line)) break;
    if (/^Rewritten at the end of every session/i.test(line)) continue;
    lead.push(line);
  }

  const next: string[] = [];
  const nextAt = lines.findIndex((l) => /^##\s+What is next/i.test(l));
  if (nextAt >= 0) {
    for (let i = nextAt + 1; i < lines.length; i++) {
      const line = lines[i] ?? '';
      if (/^##\s/.test(line)) break;
      const item = /^(\d+)\.\s+\*\*(.+?)\*\*/.exec(line);
      if (item) next.push(`${item[1]}. ${(item[2] ?? '').replace(/[.:]$/, '')}`);
    }
  }

  const summary = lead.join('\n').trim() || 'handoff.md has no lead block.';
  return next.length ? `${summary}\n\nNext, in order:\n\n${next.join('\n')}` : summary;
}

export function composeFaceBoot(input: FaceBootInput): string {
  const out: string[] = [];

  out.push(BOOT_MARKER, '', '# FACE-BOOT', '');
  out.push(
    `Written for JARVIS Head, which reaches this repo only through github.com. Baked ${input.bakedAt} on ${input.machine}.`,
    '',
    'In order: the codex index, mail waiting for the Face, what is broken on the board, and the state',
    'of the Hands. The Hands cannot hear you directly. Dictate a message and William carries it',
    'through the SkynetOS mailbox panel; the protocol is in `codex/mailbox/README.md`.',
    ''
  );

  out.push('## 1. Codex index', '', '`codex/index.md`, verbatim.', '');
  out.push(input.index?.trim() ? fenced(input.index) : '`codex/index.md` is missing.', '');

  const mail = [...input.mail].sort((a, b) => b.file.localeCompare(a.file));
  const shown = mail.slice(0, MAIL_LIMIT);
  out.push(`## 2. Mail for the Face (${mail.length} unread, newest first)`, '');
  if (!mail.length) out.push('Nothing waiting in `codex/mailbox/to-face/`.', '');
  for (const message of shown) {
    out.push(
      `### ${message.subject}`,
      '',
      `\`${message.file}\`, from ${message.from}${message.sentAt ? `, sent ${message.sentAt}` : ''}`,
      '',
      fenced(message.body),
      ''
    );
  }
  if (mail.length > shown.length) {
    out.push(
      `${mail.length - shown.length} older message(s) not shown. They stay in \`codex/mailbox/to-face/\` until William archives them from the panel.`,
      ''
    );
  }

  out.push('## 3. Board truth', '', `Resolved against the disk of ${input.machine} at bake time. Another machine may differ.`, '');
  out.push('| Board | File | Nodes | Traces | Unresolved | Provisional |', '|---|---|---:|---:|---:|---:|');
  for (const board of input.boards) {
    out.push(
      `| ${board.name} (\`${board.id}\`) | \`${board.file}\` | ${board.nodeCount} | ${board.edgeCount} | ${board.faults.length} | ${board.provisional.length} |`
    );
  }
  out.push('');

  const faults = input.boards.flatMap((b) => b.faults.map((f) => ({ board: b.id, ...f })));
  out.push(`### Unresolved targets (${faults.length})`, '');
  if (!faults.length) out.push('Every target on every board resolves.');
  for (const f of faults) {
    out.push(`- \`${f.board}\` / ${f.label} (\`${f.nodeId}\`, ${f.kind}): **${f.state.toUpperCase()}** \`${f.target}\``);
  }
  out.push('');

  const provisional = input.boards.flatMap((b) => b.provisional.map((p) => ({ board: b.id, ...p })));
  out.push(`### Provisional nodes (${provisional.length})`, '', 'Placed on the board but not yet confirmed as bound to anything real.', '');
  if (!provisional.length) out.push('None.');
  for (const p of provisional) out.push(`- \`${p.board}\` / ${p.label} (\`${p.nodeId}\`, ${p.kind})`);
  out.push('');

  out.push('## 4. State of the Hands', '', 'Compressed from `handoff.md`, which is linked from the repo root.', '');
  out.push(handoffState(input.handoff), '');

  // After the four the Face asked for, so their numbering holds. It is here at all because the
  // Face owns this file and has no other way to see what is actually in force.
  out.push(
    '## 5. Standing orders in force',
    '',
    '`codex/face-brief.md`, verbatim. SkynetOS fills in its header (`written-at`, `supersedes`,',
    '`source`) when a `standing:` message arrives; you write only the body.',
    ''
  );
  out.push(input.standing?.trim() ? fenced(input.standing) : 'None. `codex/face-brief.md` has not been written.', '');

  if (input.tools.length) {
    out.push(
      '## 6. Hands tool surface',
      '',
      `The skynet MCP server (\`tools/skynet-mcp.mjs\`), ${input.tools.length} tools. Name them when you ask the Hands for something.`,
      'The Hands also have a shell, git, and read/write access to everything under `C:/dev`.',
      '',
      input.tools.map((t) => `\`${t}\``).join(' · '),
      ''
    );
  }

  return `${out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
}

/** Two bakes that differ only in their timestamp are the same bake, and are not rewritten. */
export function sameBake(a: string, b: string): boolean {
  const strip = (s: string) => s.replace(/\r\n/g, '\n').replace(BAKED_LINE, '');
  return strip(a) === strip(b);
}
